### ISSUE TITLE
Update distutils.version.LooseVersion in readthedocs.py

### ISSUE THREAD

**Issue by dihm** [readthedocs/readthedocs-sphinx-ext#106]
Would it be possible to replace `distutils.version.LooseVersion` with the more modern `packaging.Version.Version`? These are functionally equivalent, but would necessitate adding the `packaging` package as a dependency.

The reason is admittedly a little convoluted. I have a [build on RTD failing](https://readthedocs.org/projects/labscript-devices/builds/16774123/) due the project incorporating detection of double import errors and setuptools shipping a local distutils hack (in anticipation of distutils being deprecated) that results in a double import when directly calling distutils. While that may or may not be intended behavior on the part of setuptools, I'd just as soon remove direct calls to distutils since it is [deprecated and will be removed by python 3.12](https://peps.python.org/pep-0632/#migration-advice).

**Comment by stsewd** [comment]
Looks like we could also use `pkg_resources.parse_version`

https://setuptools.pypa.io/en/latest/userguide/distribution.html#specifying-your-project-s-version

Which seems to  be available since setuptools 8.3
 https://github.com/pypa/setuptools/blob/b22fd831fd0bf735beb1ea97f630d8fb1c4c5158/pkg_resources/__init__.py#L201-L205

**Comment by astrojuanlu** [comment]
`pkg_resources.parse_version` uses a vendored copy of pypa/packaging under the hood, better cut the middle man?

**Comment by stsewd** [comment]
but that way we won't need to install another package

**Comment by dihm** [comment]
Obviously, I'm fine with whatever choice. Only thing I would add is that the official migration advice from [PEP 632](https://peps.python.org/pep-0632/#migration-advice) (which deprecates `distutils`) is to use the `packaging` package.

Anyway, as the interloper, I'm fine with whatever choice is made, and I'm happy to make a PR if that would be considered helpful.

**Comment by ericholscher** [comment]
This seems like a reasonable thing to do, assuming it implements the same logic. I don't care strongly about adding a dependency, if it's the recommended approach. I thought we were already using the `packaging` module: https://github.com/readthedocs/readthedocs.org/blob/1ab39402a493933493aec4c02b76da24e2c9862a/requirements/pip.txt#L91

**Comment by stsewd** [comment]
https://setuptools.pypa.io/en/latest/pkg_resources.html

> Use of pkg_resources is discouraged in favor of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Please consider using those libraries instead of pkg_resources.

Looks like that package is also deprecated, we could just specify packaging without any boundaries in the version, so any version would be used, we already do that with requests https://github.com/readthedocs/readthedocs-sphinx-ext/blob/abf2d843627ceef4b82c0dac31aaa6ab2bd19d4f/setup.py#L13

**Comment by ericholscher** [comment]
Yea, specifying it without a pin seems reasonable as an approach. We can try it and see if we hit any new issues with it. 🙃
