### ISSUE TITLE
Is it possible to exclude some parts of extension?

### ISSUE THREAD

**Issue by ItsAleph** [readthedocs/readthedocs-sphinx-ext#113]
In our project, the `external_version_warning.py` causes PR builds to include admonition at the top of the page, and we would be okay with that [if it didn't insert it in sidebar too..](https://disnake--722.org.readthedocs.build/en/722/api/index.html)
From the raw build logs, i've seen that RTD automatically injects this extension to the beginning of `extensions` config var (`extensions.insert(0, "readthedocs_ext")`). Can you please investigate this issue, or do you have some solution to this (i.e., ignoring PR build warning)? (in best case we dont want to fully ignore this extension, since, e.g., admonitions about deprecated version are pretty useful)
Thanks in advance!

**Comment by humitos** [comment]
Hi @ItsAleph! Did you solve this issue by yourself? If that's the case, would you like to share the solution? Thanks 🙏🏼

**Comment by ItsAleph** [comment]
We solved it by monkeypatching this extension at build time, replacing your listener with custom one. I've opened PR that eliminates this issue (#114).
