### ISSUE TITLE
RTD builds fail when not using Sphinx basic theme assets and `fail_on_warning` is asserted

### ISSUE THREAD

**Issue by 2bndy5** [readthedocs/readthedocs-sphinx-ext#128]
I am helping maintain the sphinx-immaterial theme which does not use any assets from the Sphinx basic theme. In fact, we explicitly inherit from the basic theme but don't include certain JS files (we're using a different search implementation).

This causes a warning to get emitted when using sphinx-immaterial theme on RTD. And if the `sphinx.fail_on_warning` option is enabled, then the build fails entirely. The warning comes from
https://github.com/readthedocs/readthedocs-sphinx-ext/blob/7c60d1646c12ac0b83d61abfbdd5bcd77d324124/readthedocs_ext/readthedocs.py#L273

## Questions
1. What is the searchtools.js needed for? Is sphinx-immaterial breaking a feature specific to RTD?
2. Can we add to the warning invocation in a way that will allow users' conf.py to ignore it?
   ```py
           log.warning('Missing searchtools: {}'.format(searchtools_file), type="readthedocs", subtype="searchtools")
   ```
   Now it could be theoretically ignored with the following conf.py settings:
   ```py
   suppress_warnings = ["readthedocs.searchtools"]
   ```

## History
Originally noted in jbms/sphinx-immaterial#283

**Comment by humitos** [comment]
This definitely looks like an issue in our own Sphinx extension, not on your project or theme

**Comment by 2bndy5** [comment]
I agree that it isn't great to rely on assets that optionally exist; Sphinx doesn't require a theme inherit and use assets from the basic theme.

Still any thoughts on the questions posed in OP?

**Comment by 2bndy5** [comment]
Ping.

I can submit a PR for question 2 if that's acceptable. I could be productive if we had an answer for question 1 though.

**Comment by chrisjsewell** [comment]
@humitos?

**Comment by humitos** [comment]
I opened #129 that will solve this issue.

**Comment by chrisjsewell** [comment]
Brilliant thanks @humitos 🙏
