### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs-sphinx-ext#18]
We're pushing more functionality here, we should be testing this for output. Basing some testing off of some of our test cases from sphinx-autoapi or sphinxcontrib-dotnetdomain would be good here.

We should also look into testing across sphinx versions with a tox config that uses generated envlist, such as:

https://testrun.org/tox/latest/config.html#generating-environments-conditional-settings

**Comment by ericholscher** [comment]
I have basic integration tests in the latest PR.

**Comment by agjohnson** [comment]
Yeah, basic tests there look good, it would be a good idea to move in some stricter testing. Infinitely better to have basic tests here at least though. Testing across sphinx versions will be a great addition as well, if we can provide the right test cases.

**Comment by stsewd** [comment]
> Testing across sphinx versions will be a great addition as well, if we can provide the right test cases.

We already do that, not sure how to improve the current tests, I haven't look at them so close anyway

**Comment by stsewd** [comment]
We are already testing across several sphinx versions.
