### ISSUE TITLE
Don't set "canonical" URL twice?

### ISSUE THREAD

**Issue by mgeier** [readthedocs/readthedocs-sphinx-ext#83]
Since Sphinx 1.8, there is `html_baseurl`: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_baseurl

This is used to set the "canonical" URL of the page.

I think `readthedocs-sphinx-ext` should check for this and, if specified, *not* emit the "canonical" url a second time.

An example illustrating the problem is the Sphinx homepage itself https://www.sphinx-doc.org/en/master/.

In line 19, the HTML source contains:

```html
<link rel="canonical" href="https://www.sphinx-doc.org/en/master/index.html" />
```

And a bit further down, starting with line 65, those lines appear:

```html
<!-- RTD Extra Head -->

<!-- 
Always link to the latest version, as canonical.
http://docs.readthedocs.org/en/latest/canonical.html
-->
<link rel="canonical" href="https://www.sphinx-doc.org/en/master/" />
```

I'm not sure what the consequences of two "canonical" urls are.
Interestingly, the two URLs are not even the same!
This happens only on the "index" page, though, on other pages the URLs are identical.

I don't know if any of this matters, but I guess it would be better to have only one "canonical" URL, right?

BTW, the URL should be escaped, see #82.

**Comment by mgeier** [comment]
Any comments on this?

This might become more relevant if and when the Open Graph Protocol will be supported (see https://github.com/sphinx-doc/sphinx/pull/7974).

**Comment by stsewd** [comment]
I'll see if I can put this one into our roadmap

**Comment by mgeier** [comment]
Any news on this?

**Comment by stsewd** [comment]
I was thinking to take a look at this today :D
